version: '3'
services:
  nginx:
    image: "${NGINX_IMAGE_NAME}:${NGINX_IMAGE_TAG}"
    restart: always
    ports:
      - "9000:80"
    volumes:
      - web-static:/app/static

  postgres:
    image: postgres:13.1
    restart: always
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=adaptive_learning
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  web:
    image: "${BACKEND_IMAGE_NAME}:${BACKEND_IMAGE_TAG}"
    command: secrethub run ./scripts/docker/run-dev.sh
    environment:
      - SECRETHUB_CREDENTIAL
      - ADAPTIVE_LEARNING_DB_HOST=postgres
      - DJANGO_SECRET_KEY="randomkey1234"
      - ADAPTIVE_LEARNING_EMAIL_BACKEND
    depends_on:
      - postgres
      - nginx
    volumes:
      - web-static:/app/static
      - ./mails:/tmp/app-messages/mails

volumes:
  web-static: 
      