version: '3'
services:
  nginx:
    image: "${NGINX_IMAGE_NAME}:${NGINX_IMAGE_TAG}"
    restart: always
    ports:
      - "80:80"
    volumes:
      - web-static:/app/static

  postgres:
    image: postgres:13.1
    restart: always
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=adaptive_learning
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  web:
    image: "${BACKEND_IMAGE_NAME}:${BACKEND_IMAGE_TAG}"
    command: ./scripts/docker/run-dev.sh
    environment:
      - SECRETHUB_CREDENTIAL
      - ADAPTIVE_LEARNING_DB_HOST=postgres
    depends_on:
      - postgres
      - nginx
    volumes:
      - web-static:/app/static
    
  frontend:
    build:
        context: .
        target: test
    environment: 
       - CI
    command: ./docker/test.sh
    depends_on:
      - web

volumes:
  web-static: 
      